#!/bin/bash

VERSION=0.8.0
PACKAGE=xxhash
TOOL=xxh64sum
DIRECTORY=$(dirname $0)

OPTIONS=""
for STORAGE in "${STORAGES[@]}"
do
	if [ -d "$STORAGE" ]; then
		OPTIONS=$OPTIONS" -B $STORAGE"
	fi
done

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
